#!/usr/bin/env bash

java -version
script/update-project.clj
cd server
lein run -m clj-kondo.lsp-server.impl.version
lein uberjar
cd target
for filename in *standalone.jar;
do cp "$filename" "clj-kondo-$filename";
done
cd ..
cp target/lsp-*-standalone.jar ../vscode-extension/clj-kondo.lsp-standalone.jar
